set_property SRC_FILE_INFO {cfile:/home/lxeng99/PTC/ptc-firmware/reference_design/Vivado/ME-XU5-5EV-2I-D12E/Mercury_XU5_PE1.srcs/sources_1/bd/Mercury_XU5/ip/Mercury_XU5_zynq_ultra_ps_e_0/Mercury_XU5_zynq_ultra_ps_e_0/Mercury_XU5_zynq_ultra_ps_e_0_in_context.xdc rfile:../../../Mercury_XU5_PE1.srcs/sources_1/bd/Mercury_XU5/ip/Mercury_XU5_zynq_ultra_ps_e_0/Mercury_XU5_zynq_ultra_ps_e_0/Mercury_XU5_zynq_ultra_ps_e_0_in_context.xdc id:1 order:EARLY scoped_inst:Mercury_XU5_i/zynq_ultra_ps_e} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lxeng99/PTC/ptc-firmware/reference_design/Vivado/ME-XU5-5EV-2I-D12E/Mercury_XU5_PE1.srcs/sources_1/bd/Mercury_XU5/ip/Mercury_XU5_ddr4_0/Mercury_XU5_ddr4_0/Mercury_XU5_ddr4_0_in_context.xdc rfile:../../../Mercury_XU5_PE1.srcs/sources_1/bd/Mercury_XU5/ip/Mercury_XU5_ddr4_0/Mercury_XU5_ddr4_0/Mercury_XU5_ddr4_0_in_context.xdc id:2 order:EARLY scoped_inst:Mercury_XU5_i/ddr4} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lxeng99/PTC/ptc-firmware/reference_design/Vivado/ME-XU5-5EV-2I-D12E/Mercury_XU5_PE1.srcs/sources_1/bd/Mercury_XU5/ip/Mercury_XU5_clk_wiz_0_0/Mercury_XU5_clk_wiz_0_0/Mercury_XU5_clk_wiz_0_0_in_context.xdc rfile:../../../Mercury_XU5_PE1.srcs/sources_1/bd/Mercury_XU5/ip/Mercury_XU5_clk_wiz_0_0/Mercury_XU5_clk_wiz_0_0/Mercury_XU5_clk_wiz_0_0_in_context.xdc id:3 order:EARLY scoped_inst:Mercury_XU5_i/clk_wiz_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lxeng99/PTC/ptc-firmware/reference_design/src/Mercury_XU5_PE1.tcl rfile:../../../../../src/Mercury_XU5_PE1.tcl id:4 unmanaged:yes} [current_design]
current_instance Mercury_XU5_i/zynq_ultra_ps_e
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 480.004 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
current_instance Mercury_XU5_i/ddr4
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 9.996 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports c0_sys_clk_p] -edges {1 2 3} -edge_shift {0.000 1.666 3.332} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports c0_sys_clk_p] -edges {1 2 3} -edge_shift {0.000 -3.332 -6.664} [get_ports {}]
current_instance
current_instance Mercury_XU5_i/clk_wiz_0
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 40.000 80.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 10.000 20.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 -6.000 -12.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 -6.000 -12.000} [get_ports {}]
current_instance
set_property src_info {type:XDC file:4 line:32 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN W12   IOSTANDARD LVCMOS18  } [get_ports {IOA_D0_P}]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN W11   IOSTANDARD LVCMOS18  } [get_ports {IOA_D1_N}]
set_property src_info {type:XDC file:4 line:34 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE15  IOSTANDARD LVCMOS18  } [get_ports {IOA_D2_P}]
set_property src_info {type:XDC file:4 line:35 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE14  IOSTANDARD LVCMOS18  } [get_ports {IOA_D3_N}]
set_property src_info {type:XDC file:4 line:36 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE13  IOSTANDARD LVCMOS18  } [get_ports {IOA_D4_P}]
set_property src_info {type:XDC file:4 line:37 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF13  IOSTANDARD LVCMOS18  } [get_ports {IOA_D5_N}]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG13  IOSTANDARD LVCMOS18  } [get_ports {IOA_D6_P}]
set_property src_info {type:XDC file:4 line:39 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH13  IOSTANDARD LVCMOS18  } [get_ports {IOA_D7_N}]
set_property src_info {type:XDC file:4 line:40 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB11  IOSTANDARD LVCMOS18  } [get_ports {IOA_D8_P}]
set_property src_info {type:XDC file:4 line:41 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC11  IOSTANDARD LVCMOS18  } [get_ports {IOA_D9_N}]
set_property src_info {type:XDC file:4 line:42 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN W14   IOSTANDARD LVCMOS18  } [get_ports {IOA_D10_P}]
set_property src_info {type:XDC file:4 line:43 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN W13   IOSTANDARD LVCMOS18  } [get_ports {IOA_D11_N}]
set_property src_info {type:XDC file:4 line:44 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y14   IOSTANDARD LVCMOS18  } [get_ports {IOA_D12_P}]
set_property src_info {type:XDC file:4 line:45 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y13   IOSTANDARD LVCMOS18  } [get_ports {IOA_D13_N}]
set_property src_info {type:XDC file:4 line:46 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y12   IOSTANDARD LVCMOS18  } [get_ports {IOA_D14_P}]
set_property src_info {type:XDC file:4 line:47 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA12  IOSTANDARD LVCMOS18  } [get_ports {IOA_D15_N}]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG14  IOSTANDARD LVCMOS18  } [get_ports {IOA_D16_P}]
set_property src_info {type:XDC file:4 line:49 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH14  IOSTANDARD LVCMOS18  } [get_ports {IOA_D17_N}]
set_property src_info {type:XDC file:4 line:50 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA13  IOSTANDARD LVCMOS18  } [get_ports {IOA_D18_P}]
set_property src_info {type:XDC file:4 line:51 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB13  IOSTANDARD LVCMOS18  } [get_ports {IOA_D19_N}]
set_property src_info {type:XDC file:4 line:52 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD15  IOSTANDARD LVCMOS18  } [get_ports {IOA_D20_P}]
set_property src_info {type:XDC file:4 line:53 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD14  IOSTANDARD LVCMOS18  } [get_ports {IOA_D21_N}]
set_property src_info {type:XDC file:4 line:54 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD11  IOSTANDARD LVCMOS18  } [get_ports {IOA_D22_P}]
set_property src_info {type:XDC file:4 line:55 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD10  IOSTANDARD LVCMOS18  } [get_ports {IOA_D23_N}]
set_property src_info {type:XDC file:4 line:56 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB14  IOSTANDARD LVCMOS18  } [get_ports {IOA_CLK1_N}]
set_property src_info {type:XDC file:4 line:57 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB15  IOSTANDARD LVCMOS18  } [get_ports {IOA_CLK0_P}]
set_property src_info {type:XDC file:4 line:60 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA11  IOSTANDARD LVCMOS18  } [get_ports {IOB_D0_P}]
set_property src_info {type:XDC file:4 line:61 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA10  IOSTANDARD LVCMOS18  } [get_ports {IOB_D1_N}]
set_property src_info {type:XDC file:4 line:62 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y9    IOSTANDARD LVCMOS18  } [get_ports {IOB_D2_P}]
set_property src_info {type:XDC file:4 line:63 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA8   IOSTANDARD LVCMOS18  } [get_ports {IOB_D3_N}]
set_property src_info {type:XDC file:4 line:64 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN W10   IOSTANDARD LVCMOS18  } [get_ports {IOB_D4_P}]
set_property src_info {type:XDC file:4 line:65 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y10   IOSTANDARD LVCMOS18  } [get_ports {IOB_D5_N}]
set_property src_info {type:XDC file:4 line:66 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC12  IOSTANDARD LVCMOS18  } [get_ports {IOB_D6_P}]
set_property src_info {type:XDC file:4 line:67 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD12  IOSTANDARD LVCMOS18  } [get_ports {IOB_D7_N}]
set_property src_info {type:XDC file:4 line:68 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG10  IOSTANDARD LVCMOS18  } [get_ports {IOB_D8_P}]
set_property src_info {type:XDC file:4 line:69 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH10  IOSTANDARD LVCMOS18  } [get_ports {IOB_D9_N}]
set_property src_info {type:XDC file:4 line:70 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE10  IOSTANDARD LVCMOS18  } [get_ports {IOB_D10_P}]
set_property src_info {type:XDC file:4 line:71 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF10  IOSTANDARD LVCMOS18  } [get_ports {IOB_D11_N}]
set_property src_info {type:XDC file:4 line:72 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH12  IOSTANDARD LVCMOS18  } [get_ports {IOB_D12_P}]
set_property src_info {type:XDC file:4 line:73 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH11  IOSTANDARD LVCMOS18  } [get_ports {IOB_D13_N}]
set_property src_info {type:XDC file:4 line:74 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF11  IOSTANDARD LVCMOS18  } [get_ports {IOB_D14_P}]
set_property src_info {type:XDC file:4 line:75 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG11  IOSTANDARD LVCMOS18  } [get_ports {IOB_D15_N}]
set_property src_info {type:XDC file:4 line:76 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB10  IOSTANDARD LVCMOS18  } [get_ports {IOB_D16_SC0_DIP1_N}]
set_property src_info {type:XDC file:4 line:77 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB9   IOSTANDARD LVCMOS18  } [get_ports {IOB_D17_SC1_DIP2_N}]
set_property src_info {type:XDC file:4 line:78 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E10   IOSTANDARD LVCMOS18  } [get_ports {IOB_D20_SC4_BTN0_N}]
set_property src_info {type:XDC file:4 line:79 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D10   IOSTANDARD LVCMOS18  } [get_ports {IOB_D21_SC5_BTN1_N}]
set_property src_info {type:XDC file:4 line:80 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E12   IOSTANDARD LVCMOS18  } [get_ports {IOB_D22_SC6_BTN2_N}]
set_property src_info {type:XDC file:4 line:81 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D11   IOSTANDARD LVCMOS18  } [get_ports {IOB_D23_SC7_BTN3_N}]
set_property src_info {type:XDC file:4 line:82 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC13  IOSTANDARD LVCMOS18  } [get_ports {IOB_CLK1_N}]
set_property src_info {type:XDC file:4 line:83 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC14  IOSTANDARD LVCMOS18  } [get_ports {IOB_CLK0_P}]
set_property src_info {type:XDC file:4 line:90 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA02_N}]
set_property src_info {type:XDC file:4 line:91 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N9    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA02_P}]
set_property src_info {type:XDC file:4 line:92 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA03_N}]
set_property src_info {type:XDC file:4 line:93 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA03_P}]
set_property src_info {type:XDC file:4 line:94 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA04_N}]
set_property src_info {type:XDC file:4 line:95 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA04_P}]
set_property src_info {type:XDC file:4 line:96 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J9    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA05_N}]
set_property src_info {type:XDC file:4 line:97 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K9    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA05_P}]
set_property src_info {type:XDC file:4 line:98 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA06_N}]
set_property src_info {type:XDC file:4 line:99 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA06_P}]
set_property src_info {type:XDC file:4 line:100 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA07_N}]
set_property src_info {type:XDC file:4 line:101 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H9    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA07_P}]
set_property src_info {type:XDC file:4 line:102 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA08_N}]
set_property src_info {type:XDC file:4 line:103 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA08_P}]
set_property src_info {type:XDC file:4 line:104 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA09_N}]
set_property src_info {type:XDC file:4 line:105 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA09_P}]
set_property src_info {type:XDC file:4 line:106 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA10_N}]
set_property src_info {type:XDC file:4 line:107 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA10_P}]
set_property src_info {type:XDC file:4 line:108 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA11_N}]
set_property src_info {type:XDC file:4 line:109 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA11_P}]
set_property src_info {type:XDC file:4 line:110 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN P6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA12_N}]
set_property src_info {type:XDC file:4 line:111 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN P7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA12_P}]
set_property src_info {type:XDC file:4 line:112 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA13_N}]
set_property src_info {type:XDC file:4 line:113 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA13_P}]
set_property src_info {type:XDC file:4 line:114 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA14_N}]
set_property src_info {type:XDC file:4 line:115 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA14_P}]
set_property src_info {type:XDC file:4 line:116 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA15_N}]
set_property src_info {type:XDC file:4 line:117 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA15_P}]
set_property src_info {type:XDC file:4 line:118 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA16_N}]
set_property src_info {type:XDC file:4 line:119 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA16_P}]
set_property src_info {type:XDC file:4 line:120 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA19_N}]
set_property src_info {type:XDC file:4 line:121 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA19_P}]
set_property src_info {type:XDC file:4 line:122 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA20_N}]
set_property src_info {type:XDC file:4 line:123 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA20_P}]
set_property src_info {type:XDC file:4 line:124 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA21_N}]
set_property src_info {type:XDC file:4 line:125 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA21_P}]
set_property src_info {type:XDC file:4 line:126 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D9    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA22_N}]
set_property src_info {type:XDC file:4 line:127 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E9    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA22_P}]
set_property src_info {type:XDC file:4 line:128 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B9    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA23_N}]
set_property src_info {type:XDC file:4 line:129 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C9    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA23_P}]
set_property src_info {type:XDC file:4 line:130 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA24_N}]
set_property src_info {type:XDC file:4 line:131 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA24_P}]
set_property src_info {type:XDC file:4 line:132 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA25_N}]
set_property src_info {type:XDC file:4 line:133 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A9    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA25_P}]
set_property src_info {type:XDC file:4 line:134 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA26_N}]
set_property src_info {type:XDC file:4 line:135 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA26_P}]
set_property src_info {type:XDC file:4 line:136 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA27_N}]
set_property src_info {type:XDC file:4 line:137 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA27_P}]
set_property src_info {type:XDC file:4 line:138 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA28_N}]
set_property src_info {type:XDC file:4 line:139 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA28_P}]
set_property src_info {type:XDC file:4 line:140 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA29_N}]
set_property src_info {type:XDC file:4 line:141 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA29_P}]
set_property src_info {type:XDC file:4 line:142 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA30_N}]
set_property src_info {type:XDC file:4 line:143 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA30_P}]
set_property src_info {type:XDC file:4 line:144 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA31_N}]
set_property src_info {type:XDC file:4 line:145 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA31_P}]
set_property src_info {type:XDC file:4 line:146 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA32_N}]
set_property src_info {type:XDC file:4 line:147 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA32_P}]
set_property src_info {type:XDC file:4 line:148 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA33_N}]
set_property src_info {type:XDC file:4 line:149 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA33_P}]
set_property src_info {type:XDC file:4 line:150 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA00_CC_N}]
set_property src_info {type:XDC file:4 line:151 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA00_CC_P}]
set_property src_info {type:XDC file:4 line:152 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA01_CC_N}]
set_property src_info {type:XDC file:4 line:153 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA01_CC_P}]
set_property src_info {type:XDC file:4 line:154 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA17_CC_N}]
set_property src_info {type:XDC file:4 line:155 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA17_CC_P}]
set_property src_info {type:XDC file:4 line:156 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA18_CC_N}]
set_property src_info {type:XDC file:4 line:157 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA18_CC_P}]
set_property src_info {type:XDC file:4 line:158 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L2    IOSTANDARD LVCMOS18  } [get_ports {FMC_CLK0_M2C_N}]
set_property src_info {type:XDC file:4 line:159 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L3    IOSTANDARD LVCMOS18  } [get_ports {FMC_CLK0_M2C_P}]
set_property src_info {type:XDC file:4 line:160 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C2    IOSTANDARD LVCMOS18  } [get_ports {FMC_CLK1_M2C_N}]
set_property src_info {type:XDC file:4 line:161 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C3    IOSTANDARD LVCMOS18  } [get_ports {FMC_CLK1_M2C_P}]
set_property src_info {type:XDC file:4 line:164 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D12   IOSTANDARD LVCMOS18  } [get_ports {I2C_SCL_PL}]
set_property src_info {type:XDC file:4 line:165 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C12   IOSTANDARD LVCMOS18  } [get_ports {I2C_SDA_PL}]
set_property src_info {type:XDC file:4 line:200 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H2    IOSTANDARD LVCMOS18  } [get_ports {LED1_N}]
set_property src_info {type:XDC file:4 line:201 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN P9    IOSTANDARD LVCMOS18  } [get_ports {LED2_N}]
set_property src_info {type:XDC file:4 line:202 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K5    IOSTANDARD LVCMOS18  } [get_ports {LED3_N}]
set_property src_info {type:XDC file:4 line:205 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD4   IOSTANDARD DIFF_SSTL12_DCI} [get_ports {CLK100_PL_N}]
set_property src_info {type:XDC file:4 line:206 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD5   IOSTANDARD DIFF_SSTL12_DCI} [get_ports {CLK100_PL_P}]
set_property src_info {type:XDC file:4 line:210 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH1   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_BA[0]}]
set_property src_info {type:XDC file:4 line:211 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF1   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_BA[1]}]
set_property src_info {type:XDC file:4 line:212 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG1   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_BG[0]}]
set_property src_info {type:XDC file:4 line:213 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD9   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_BG[1]}]
set_property src_info {type:XDC file:4 line:214 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH6   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_CKE[0]}]
set_property src_info {type:XDC file:4 line:215 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB6   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[0]}]
set_property src_info {type:XDC file:4 line:216 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC6   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[1]}]
set_property src_info {type:XDC file:4 line:217 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE9   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[2]}]
set_property src_info {type:XDC file:4 line:218 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE8   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[3]}]
set_property src_info {type:XDC file:4 line:219 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB8   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[4]}]
set_property src_info {type:XDC file:4 line:220 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC8   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[5]}]
set_property src_info {type:XDC file:4 line:221 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB7   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[6]}]
set_property src_info {type:XDC file:4 line:222 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC7   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[7]}]
set_property src_info {type:XDC file:4 line:223 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE5   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[8]}]
set_property src_info {type:XDC file:4 line:224 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF5   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[9]}]
set_property src_info {type:XDC file:4 line:225 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE4   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_ODT[0]}]
set_property src_info {type:XDC file:4 line:226 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC4   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[0]}]
set_property src_info {type:XDC file:4 line:227 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC3   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[1]}]
set_property src_info {type:XDC file:4 line:228 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB4   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[2]}]
set_property src_info {type:XDC file:4 line:229 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB3   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[3]}]
set_property src_info {type:XDC file:4 line:230 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB2   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[4]}]
set_property src_info {type:XDC file:4 line:231 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC2   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[5]}]
set_property src_info {type:XDC file:4 line:232 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB1   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[6]}]
set_property src_info {type:XDC file:4 line:233 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC1   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[7]}]
set_property src_info {type:XDC file:4 line:234 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB5   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[8]}]
set_property src_info {type:XDC file:4 line:235 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG4   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[9]}]
set_property src_info {type:XDC file:4 line:236 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD1   IOSTANDARD DIFF_SSTL12_DCI} [get_ports {DDR4PL_CK_N[0]}]
set_property src_info {type:XDC file:4 line:237 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD2   IOSTANDARD DIFF_SSTL12_DCI} [get_ports {DDR4PL_CK_P[0]}]
set_property src_info {type:XDC file:4 line:238 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH9   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_CS_N[0]}]
set_property src_info {type:XDC file:4 line:239 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF8   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[10]}]
set_property src_info {type:XDC file:4 line:240 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG8   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[11]}]
set_property src_info {type:XDC file:4 line:241 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH8   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[12]}]
set_property src_info {type:XDC file:4 line:242 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH7   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[13]}]
set_property src_info {type:XDC file:4 line:243 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF7   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[14]}]
set_property src_info {type:XDC file:4 line:244 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF6   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DQ[15]}]
set_property src_info {type:XDC file:4 line:245 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH2   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_ACT_N}]
set_property src_info {type:XDC file:4 line:246 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH4   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[10]}]
set_property src_info {type:XDC file:4 line:247 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG3   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[11]}]
set_property src_info {type:XDC file:4 line:248 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH3   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[12]}]
set_property src_info {type:XDC file:4 line:249 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE3   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[13]}]
set_property src_info {type:XDC file:4 line:250 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF3   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[14]}]
set_property src_info {type:XDC file:4 line:251 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE2   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[15]}]
set_property src_info {type:XDC file:4 line:252 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF2   IOSTANDARD SSTL12_DCI} [get_ports {DDR4PL_A[16]}]
set_property src_info {type:XDC file:4 line:253 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC9   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DM[0]}]
set_property src_info {type:XDC file:4 line:254 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG9   IOSTANDARD POD12_DCI } [get_ports {DDR4PL_DM[1]}]
set_property src_info {type:XDC file:4 line:255 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE7   IOSTANDARD DIFF_POD12_DCI} [get_ports {DDR4PL_DQS_N[0]}]
set_property src_info {type:XDC file:4 line:256 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG5   IOSTANDARD DIFF_POD12_DCI} [get_ports {DDR4PL_DQS_N[1]}]
set_property src_info {type:XDC file:4 line:257 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD7   IOSTANDARD DIFF_POD12_DCI} [get_ports {DDR4PL_DQS_P[0]}]
set_property src_info {type:XDC file:4 line:258 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG6   IOSTANDARD DIFF_POD12_DCI} [get_ports {DDR4PL_DQS_P[1]}]
set_property src_info {type:XDC file:4 line:259 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G4    IOSTANDARD LVCMOS18  } [get_ports {DDR4PL_RST_N}]
set_property src_info {type:XDC file:4 line:274 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A10   IOSTANDARD LVCMOS18  } [get_ports {ETH1_MDC}]
set_property src_info {type:XDC file:4 line:275 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J11   IOSTANDARD LVCMOS18  } [get_ports {ETH1_RXD[0]}]
set_property src_info {type:XDC file:4 line:276 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J10   IOSTANDARD LVCMOS18  } [get_ports {ETH1_RXD[1]}]
set_property src_info {type:XDC file:4 line:277 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K13   IOSTANDARD LVCMOS18  } [get_ports {ETH1_RXD[2]}]
set_property src_info {type:XDC file:4 line:278 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K12   IOSTANDARD LVCMOS18  } [get_ports {ETH1_RXD[3]}]
set_property src_info {type:XDC file:4 line:279 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G11   IOSTANDARD LVCMOS18  } [get_ports {ETH1_RXCLK}]
set_property src_info {type:XDC file:4 line:280 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H11   IOSTANDARD LVCMOS18  } [get_ports {ETH1_TXD[0]}]
set_property src_info {type:XDC file:4 line:281 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G10   IOSTANDARD LVCMOS18  } [get_ports {ETH1_TXD[1]}]
set_property src_info {type:XDC file:4 line:282 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J12   IOSTANDARD LVCMOS18  } [get_ports {ETH1_TXD[2]}]
set_property src_info {type:XDC file:4 line:283 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H12   IOSTANDARD LVCMOS18  } [get_ports {ETH1_TXD[3]}]
set_property src_info {type:XDC file:4 line:284 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F12   IOSTANDARD LVCMOS18  } [get_ports {ETH1_TXCLK}]
set_property src_info {type:XDC file:4 line:285 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B11   IOSTANDARD LVCMOS18  } [get_ports {ETH1_MDIO}]
set_property src_info {type:XDC file:4 line:286 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C11   IOSTANDARD LVCMOS18  } [get_ports {ETH1_INT_N}]
set_property src_info {type:XDC file:4 line:287 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B10   IOSTANDARD LVCMOS18  } [get_ports {ETH1_RESET_N}]
set_property src_info {type:XDC file:4 line:288 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F10   IOSTANDARD LVCMOS18  } [get_ports {ETH1_RXCTL}]
set_property src_info {type:XDC file:4 line:289 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F11   IOSTANDARD LVCMOS18  } [get_ports {ETH1_TXCTL}]
