#!/bin/sh
[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

case "$1" in
    deconfig)
        /sbin/ifconfig $interface 0.0.0.0
        ;;
    renew|bound)
        /sbin/ifconfig $interface $ip netmask ${subnet:-255.255.255.0} broadcast ${broadcast:-+}
        if [ -n "$router" ] ; then
            while route del default gw 0.0.0.0 dev $interface 2>/dev/null; do :; done
            for i in $router ; do
                route add default gw $i dev $interface
            done
        fi
        ;;
esac
exit 0